Repository software-mansion/starknet.py, pull requests merged in 2022-12, with the labels that each got.

#551 Update tests after Account refactor
  starknet_py/contract.py
  starknet_py/net/account/account.py
  starknet_py/net/account/account_test.py
  starknet_py/net/signer/stark_curve_signer.py
  starknet_py/tests/e2e/account/account_client_test.py
  starknet_py/tests/e2e/account/account_test.py
  starknet_py/tests/e2e/contract_interaction/interaction_test.py
  starknet_py/tests/e2e/declare/declare_test.py
  starknet_py/tests/e2e/deploy/deployer_test.py
  starknet_py/tests/e2e/deploy_account/deploy_account_test.py
  starknet_py/tests/e2e/fixtures/account_clients.py
  starknet_py/tests/e2e/fixtures/clients.py
  starknet_py/tests/e2e/fixtures/contracts.py
  starknet_py/tests/e2e/fixtures/devnet.py
  starknet_py/tests/e2e/fixtures/misc.py
  starknet_py/tests/e2e/fixtures/proxy.py
Labels: refactor

#546 Add `Account.deploy_account` simplified flow
  starknet_py/net/account/account.py
  starknet_py/net/account/account_deployment_result.py
Labels: refactor

#564 Update docs after Account refactor
  docs/account.rst
  docs/api.rst
  docs/guide.rst
  docs/quickstart.rst
  starknet_py/net/account/account_client.py
  starknet_py/tests/e2e/docs/account_creation/test_deploy_prefunded_account.py
  starknet_py/tests/e2e/docs/guide/test_account_details.py
  starknet_py/tests/e2e/docs/guide/test_custom_signer.py
  starknet_py/tests/e2e/docs/guide/test_declaring_contracts.py
  starknet_py/tests/e2e/docs/guide/test_deploying_in_multicall.py
  starknet_py/tests/e2e/docs/guide/test_deploying_with_udc.py
  starknet_py/tests/e2e/docs/guide/test_handling_client_errors.py
  starknet_py/tests/e2e/docs/guide/test_sign_offchain_message.py
  starknet_py/tests/e2e/docs/guide/test_simple_declare_and_deploy.py
  starknet_py/tests/e2e/docs/guide/test_simple_deploy.py
  starknet_py/tests/e2e/docs/guide/test_using_cairo_serializer.py
  starknet_py/tests/e2e/docs/guide/test_using_existing_contracts.py
  starknet_py/tests/e2e/docs/quickstart/test_creating_account.py
  starknet_py/tests/e2e/docs/quickstart/test_synchronous_api.py
  starknet_py/tests/e2e/docs/quickstart/test_using_account.py
  starknet_py/tests/e2e/docs/quickstart/test_using_contract.py
Labels: refactor

#608 Remove deprecated note from the `Account creation`
  docs/account_creation.rst
  docs/guide.rst
Labels: documentation

#611 Fix SentTransaction docs
  docs/account.rst
  docs/contract.rst
  starknet_py/contract.py
  starknet_py/net/account/account_deployment_result.py
Labels: documentation, refactor

#625 Bump devnet
  poetry.lock
  pyproject.toml
Labels: dependencies
