Repository software-mansion/starknet.py, pull requests merged in 2023-04, with the labels that each got.

#911 Use newest devnet - set `--cairo-compiler-manifest` option
  .github/workflows/checks.yml
  poetry.lock
  pyproject.toml
  starknet_py/tests/e2e/declare/declare_test.py
  starknet_py/tests/e2e/docs/guide/test_cairo1_contract.py
  starknet_py/tests/e2e/fixtures/devnet.py
  starknet_py/tests/e2e/manifest-path.template
Labels: CI

#937 Get rid of `parse_type` from cairo-lang
  docs/migration_guide.rst
  starknet_py/cairo/deprecated_parse/__init__.py
  starknet_py/cairo/deprecated_parse/cairo.ebnf
  starknet_py/cairo/deprecated_parse/cairo_types.py
  starknet_py/cairo/deprecated_parse/parser.py
  starknet_py/cairo/deprecated_parse/parser_transformer.py
  starknet_py/cairo/type_parser.py
Labels: priority: high

#959 Add note about cairo1 contracts being strings in docs
  starknet_py/tests/e2e/docs/guide/test_cairo1_contract.py
Labels: 0.16.0

#977 Make cairo-lang dev dependency
  poetry.lock
  pyproject.toml
  starknet_py/hash/casm_class_hash_test.py
  starknet_py/hash/class_hash_test.py
  starknet_py/hash/sierra_class_hash_test.py
  starknet_py/hash/transaction_test.py
Labels: 0.16.0

#989 Do not test `GatewayClient` on integration
  starknet_py/tests/e2e/client/client_test.py
  starknet_py/tests/e2e/client/fixtures/transactions.py
  starknet_py/tests/e2e/client/gateway_test.py
  starknet_py/tests/e2e/mock/contracts/replace_class.cairo
Labels: tests
