Repository software-mansion/starknet.py, pull requests merged in 2023-01, with the labels that each got.

#623 Change docs theme
  docs/conf.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: documentation

#621 Replace transaction hash calculation
  starknet_py/constants.py
  starknet_py/net/models/transaction.py
  starknet_py/net/signer/stark_curve_signer.py
  starknet_py/utils/crypto/transaction_hash.py
  starknet_py/utils/crypto/transaction_hash_test.py
Labels: refactor

#624 Add style guide
  docs/development.rst
Labels: documentation

#631 Simplify `Contract` constructor
  starknet_py/contract.py
  starknet_py/contract_test.py
  starknet_py/net/account/account_test.py
  starknet_py/tests/e2e/account/account_test.py
  starknet_py/tests/e2e/contract_interaction/interaction_test.py
  starknet_py/tests/e2e/deploy/deployer_test.py
  starknet_py/tests/e2e/docs/guide/test_deploying_in_multicall.py
  starknet_py/tests/e2e/docs/guide/test_handling_client_errors.py
  starknet_py/tests/e2e/docs/guide/test_using_existing_contracts.py
  starknet_py/tests/e2e/docs/quickstart/test_synchronous_api.py
  starknet_py/tests/e2e/docs/quickstart/test_using_contract.py
  starknet_py/tests/e2e/fixtures/contracts.py
Labels: refactor

#499 Account refactor
  docs/account.rst
  docs/api.rst
  docs/contract.rst
  docs/guide.rst
  docs/migration_guide.rst
  docs/quickstart.rst
  starknet_py/contract.py
  starknet_py/contract_test.py
  starknet_py/net/account/_account_proxy.py
  starknet_py/net/account/account.py
  starknet_py/net/account/account_client.py
  starknet_py/net/account/account_deployment_result.py
  starknet_py/net/account/account_test.py
  starknet_py/net/account/base_account.py
  starknet_py/net/networks.py
  starknet_py/net/signer/base_signer.py
  starknet_py/net/signer/stark_curve_signer.py
  starknet_py/tests/e2e/account/account_client_test.py
  starknet_py/tests/e2e/account/account_test.py
  starknet_py/tests/e2e/contract_interaction/interaction_test.py
  starknet_py/tests/e2e/declare/declare_test.py
  starknet_py/tests/e2e/deploy/deployer_test.py
  starknet_py/tests/e2e/deploy_account/deploy_account_test.py
  starknet_py/tests/e2e/docs/account_creation/test_deploy_prefunded_account.py
  starknet_py/tests/e2e/docs/guide/test_account_details.py
  starknet_py/tests/e2e/docs/guide/test_custom_signer.py
  starknet_py/tests/e2e/docs/guide/test_declaring_contracts.py
  starknet_py/tests/e2e/docs/guide/test_deploying_in_multicall.py
  starknet_py/tests/e2e/docs/guide/test_deploying_with_udc.py
  starknet_py/tests/e2e/docs/guide/test_handling_client_errors.py
  starknet_py/tests/e2e/docs/guide/test_sign_offchain_message.py
  starknet_py/tests/e2e/docs/guide/test_simple_declare_and_deploy.py
  starknet_py/tests/e2e/docs/guide/test_simple_deploy.py
  starknet_py/tests/e2e/docs/guide/test_using_cairo_serializer.py
  starknet_py/tests/e2e/docs/guide/test_using_existing_contracts.py
  starknet_py/tests/e2e/docs/migration_guide/__init__.py
  starknet_py/tests/e2e/docs/migration_guide/test_account_comparison.py
  starknet_py/tests/e2e/docs/quickstart/test_creating_account.py
  starknet_py/tests/e2e/docs/quickstart/test_synchronous_api.py
  starknet_py/tests/e2e/docs/quickstart/test_using_account.py
  starknet_py/tests/e2e/docs/quickstart/test_using_contract.py
  starknet_py/tests/e2e/fixtures/account_clients.py
  starknet_py/tests/e2e/fixtures/clients.py
  starknet_py/tests/e2e/fixtures/contracts.py
  starknet_py/tests/e2e/fixtures/devnet.py
  starknet_py/tests/e2e/fixtures/misc.py
  starknet_py/tests/e2e/fixtures/proxy.py
Labels: refactor

#656 Rename `ContractDeployment.udc`-> `ContractDeployment.call`
  starknet_py/net/udc_deployer/deployer.py
  starknet_py/tests/e2e/deploy/deployer_test.py
Labels: bug

#682 Update docs
  docs/account_creation.rst
  docs/guide.rst
  docs/guide/account_and_client.rst
  docs/guide/deploying_contracts.rst
  docs/guide/ethereum_communication.rst
  docs/guide/resolving_proxy_contracts.rst
  docs/guide/serialization.rst
  docs/guide/signing.rst
  docs/guide/using_existing_contracts.rst
  docs/installation.rst
  docs/migration_guide.rst
Labels: documentation

#677 Hash module
  docs/models.rst
  starknet_py/cairo/utils.py
  starknet_py/contract.py
  starknet_py/hash/__init__.py
  starknet_py/hash/address.py
  starknet_py/hash/address_test.py
  starknet_py/hash/contract_class.py
  starknet_py/hash/contract_class_test.py
  starknet_py/hash/selector.py
  starknet_py/hash/selector_test.py
  starknet_py/hash/storage.py
  starknet_py/hash/storage_test.py
  starknet_py/hash/transaction.py
  starknet_py/hash/transaction_test.py
  starknet_py/hash/utils.py
  starknet_py/hash/utils_test.py
  starknet_py/net/account/account.py
  starknet_py/net/account/account_client.py
  starknet_py/net/models/__init__.py
  starknet_py/net/models/address.py
  starknet_py/net/models/address_test.py
  starknet_py/net/models/transaction.py
  starknet_py/net/signer/stark_curve_signer.py
  starknet_py/net/udc_deployer/deployer.py
  starknet_py/proxy/proxy_check.py
  starknet_py/tests/e2e/account/account_test.py
  starknet_py/tests/e2e/client/client_test.py
  starknet_py/tests/e2e/client/fixtures/prepare_network.py
  starknet_py/tests/e2e/client/full_node_test.py
  starknet_py/tests/e2e/client/gateway_test.py
  starknet_py/tests/e2e/contract_interaction/interaction_test.py
  starknet_py/tests/e2e/docs/account_creation/test_deploy_prefunded_account.py
  starknet_py/tests/e2e/docs/guide/test_using_cairo_serializer.py
  starknet_py/tests/e2e/fixtures/account_clients.py
  starknet_py/tests/e2e/fixtures/proxy.py
  starknet_py/tests/e2e/proxy/proxy_test.py
  starknet_py/tests/e2e/utils.py
  starknet_py/utils/crypto/crypto_test.py
  starknet_py/utils/crypto/facade.py
  starknet_py/utils/typed_data.py
Labels: refactor

#683 Replace compress and decompress program
  starknet_py/net/models/transaction.py
  starknet_py/net/models/transaction_test.py
Labels: refactor

#670 Migration guide (remove cairo lang)
  docs/migration_guide.rst
Labels: documentation

#676 Code examples! (demo)
  docs/_ext/autoclass_with_examples.py
  docs/api/abi.rst
  docs/api/data_types.rst
  docs/api/udc_deployer.rst
  docs/conf.py
  starknet_py/constants.py
  starknet_py/tests/e2e/docs/code_examples/__init__.py
  starknet_py/tests/e2e/docs/code_examples/test_deployer.py
Labels: documentation

#699 `GatewayClient` examples
  docs/_ext/autoclass_with_examples.py
  docs/api/gateway_client.rst
  starknet_py/tests/e2e/docs/code_examples/test_gateway_client.py
Labels: documentation

#707 `FullNodeClient` examples
  docs/api/full_node_client.rst
  starknet_py/net/full_node_client.py
  starknet_py/tests/e2e/docs/code_examples/test_full_node_client.py
  starknet_py/tests/e2e/docs/code_examples/test_gateway_client.py
Labels: documentation

#723 Add docs about `client.call_contract`
  docs/guide/using_existing_contracts.rst
  starknet_py/tests/e2e/docs/guide/test_using_existing_contracts.py
Labels: documentation

#696 0.14.0 migration guide
  docs/api/udc_deployer.rst
  docs/migration_guide.rst
  starknet_py/net/udc_deployer/deployer.py
Labels: documentation
